AllCops:
 Exclude:
   # You could specify set of files or dirs while you want to be ignored by rubocop
   - 'vendor/**/*'
   - 'spec/**/*'
   - 'config/**/*'
   - 'db/**/*'
   - 'bin/*'
   - 'Gemfile'
   - 'Gemfile.lock'
   - 'Rakefile'
   - 'Guardfile'
Documentation: # Disabling documentation cop
  Enabled: false
Lint/UnneededDisable:
  Enabled: false
Metrics/LineLength:
  Max: 240
